sprint-1/step-1
HunterM7/stellar-burgers pull request #1
Opened 2023-01-02 14:39 UTC by HunterM7

2023-01-02 17:28 UTC, andryxxa93 approved these changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect.

Что понравилось:
- Код аккуратный и понятный
- Проект соответствует макету
- Есть отписка от слушателя событий
- Правильная типизация ингредиента

Можете приступать к финальному этапу сдачи работы.

В pull request вы найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Рекомендация: в проекте есть некоторые проблемы с отступами в коде. Вы используете не стандартный стиль. Рекомендую установить `pretier` - он поможет следовать единому общепринятому стилю написания кода. Так же можно установить `eslint` - он позволит избежать некоторых ошибок.
https://dev.to/knowankit/setup-eslint-and-prettier-in-react-app-357b

Удачной работы!

2023-01-02 17:28 UTC, andryxxa93 commented on src/components/AppHeader/AppHeader.tsx
> +	const headerLinks = linksList.map((link, i) => {
**Необходимо исправить**
в шапке активный пункт меню будет определяться с помощью роутинга, это будет реализовано в 3 спринте, не нужно сейчас это делать через стейт

2023-01-02 17:28 UTC, andryxxa93 commented on src/hooks/useKeyPress.tsx
> +		return () => {
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-01-03 09:11 UTC, HunterM7 commented on src/components/AppHeader/AppHeader.tsx
> +	const headerLinks = linksList.map((link, i) => {
Хорошо! Сейчас сделал только для того, чтобы хотя бы нажималось и работало)

2023-01-09 19:00 UTC, HunterM7 commented
Забыл после ревью замержить проверенную работу и сделал много правок, включая то, что посоветовал предыдущий ревьюер. Поэтому снова отправляю step-1)

2023-01-10 07:35 UTC, andryxxa93 requested changes
Отличная работа. Весь требуемый функционал реализован. Здорово, что вы создали кастомные хуки, это крутой навык. 
Есть только одно замечание, которое необходимо исправить, чтобы работа была принята. 
- Добавьте проверку успешности запроса. (см. комментарий в pull-request).

Удачных правок!

2023-01-10 07:35 UTC, andryxxa93 commented on src/hooks/useFetchIngredients.ts
> +      .then((json) => {
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-01-10 09:29 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2023-01-10 09:58 UTC, merged